# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.destroy_all
Suivi.destroy_all
Survey.destroy_all
Comment.destroy_all
Engagment.destroy_all
Promess.destroy_all
Candidat.destroy_all
Commune.destroy_all
Region.destroy_all
# Daty.destroy_all

reg = ["Diana", "Sava", "Itasy", "Analamanga", "Vakinankaratra", "Bongolava", "Sofia", "Boeny",
		"Betsiboka", "Melaky", "Alaotra-Mangoro", "Atsinanana", "Analanjirofo", "Amoron'i Mania",
		"Haute Matsiatra", "Vatovavy-Fitovinany", "Atsimo-Atsinanana", "Ihorombe", "Menabe",
		"Atsimo-Andrefana", "Androy", "Anosy"]
		
alotra =["AMBANDRIKA", "AMBATONDRAZAKA", "AMBATONDRAZAKA SUBURBAINE", "AMBATOSORATRA","AMBOHIBOROMANGA","AMBOHIDAVA","AMBOHITSILAOZANA","AMPARIHINTSOKATRA","AMPITATSIMO","ANDILANATOBY","ANDROMBA","ANTANANDAVA","ANTSANGASANGA","BEJOFO","DIDY","FERAMANGA NORD","ILAFY","IMERIMANDROSO","MANAKAMBAHINY EST","MANAKAMBAHINY OUEST","SOALAZAINA","TANAMBAO BESAKAY","AMBATOMAINTY","AMBOAVORY","AMBODIMANGA","AMBODIRANO","AMBOHIJANAHARY","AMBOHIMANDROSO","AMBOHITRARIVO","AMPARAFARAVOLA","AMPASIKELY","ANDILANA NORD","ANDRANOBE","ANDREBAKELY NORD","ANDREBAKELY SUD","ANORORO","BEANANA","BEDIDY","MORARANO CHROME","RANOMAINTY","SAHAMAMY","TANAMBE","VOHIMENA","VOHITSARA","AMPONDRABE","ANDILAMENA","ANTANIMENABAKA","BEMAITSO","MAITSOKELY","MAROADABO","MAROVATO","MIARINARIVO","TANANANIFOLOLAHY","AMBALAOMBY","AMBATOHARANANA","AMBODIMERANA","AMPANDROANTRAKA","AMPASIMANEVA","ANOSIBE AN'ALA","ANTANDROKOMBY","LONGOZABE","NIAROVANA","TRATRAMARINA","TSARAVINANY","AMBATOVOLA","AMBOASARY","AMBOHIBARY","AMBOHIDRONONO","AMPASIPOTSY GARE","AMPASIPOTSY MANDIALAZA","ANALASOA","ANDAINGO","ANDASIBE","ANOSIBE IFODY","ANTANANDAVA","ANTANIDITRA","BEFORONA","BELAVABARY","BEMBARY","FIERENANA","LAKATO","MANDIALAZA","MANGARIVOTRA (EX  BEPARASY)","MORAMANGA","MORARANO GARE","SABOTSY ANJIRO","VODIRIANA"]

amoro=["AMBATOFINANDRAHANA","AMBATOMIFANONGOA","AMBONDROMISOTRA","AMBOROMPOTSY","FENOARIVO","ITREMO","MANDROSONORO","MANGATABOAHANGY","SOAVINA","ALAKAMISY AMBOHIJATO","AMBALAMANAKANA","AMBATOFITORAHANA","AMBINANINDRANO","AMBOHIMITOMBO I","AMBOHIMITOMBO II","AMBOHIPERIVOANA","AMBOSITRA","AMBOSITRA BANLIEUE","ANDINA","ANKAZOAMBO","ANKAZOTSARARAVINA","ANTOETRA","FAHIZAY","IHADILANANA AMBOHINAMBOARINA","ILAKA CENTRE","IMERINA IMADY","IVATO","IVONY MIARAMIASA","KIANJANDRAKEFINA","MAHAZINA AMBOHIPIERENANA","MAROSOA","SAHATSIHO AMBOHIMANJAKA","TSARASAOTRA","VOHIDAHY","ALAKAMISY AMBOHIMAHAZO","ANKARINORO","BETSIMISOTRA","FANDRIANA","FIADANANA","IMITO","ISANDRANDAHY AMBONY","MAHAZOARIVO","MIARINAVARATRA","MILAMAINA","SAHAMADIO FISAKANA","SANDRANDAHY","SOANAKAMBANA","TATAMALAZA","TSARAZAZA","AMBATOMARINA","AMBOHIMAHAZO","AMBOHIMILANJA","AMBOHIPO","AMBOVOMBE CENTRE","ANDAKATANY","ANJOMA NANDIHIZANA","ANJOMAN ' ANKONA","ILANJANA","SOATANANA","TALATA VOHIMENA","VINANY ANDAKATANIKELY"]

analamanga=["AMBATO","AMBATOLAMPY","AMBOHIDRATRIMO","AMBOHIMANJAKA","AMBOHIMPIHAONANA","AMBOHITRIMANJAKA","AMPANGABE","AMPANOTOKANA","ANJANADORIA","ANOSIALA","ANTANETIBE MAHAZAZA","ANTEHIROKA","ANTSAHAFILO","AVARATSENA","FIADANANA","IARINARIVO","IVATO","MAHABO","MAHEREZA","MAHITSY","MANANJARA","MANJAKAVARADRANO","MERIMANDROSO","TALATAMATY","ALAROBIA VATOSOLA","ALATSINAINY BAKARO","AMBOHIMIADANA","ANDOHARIANA","ANDRAMASINA","ANJOMA FALIARIVO","ANOSIBE TRIMOLOHARANO","ANTOTOHAZO","FITSINJOVANA BAKARO","MANDROSOA","MORARANO SOAFIRAISANA","SABOTSY AMBOHITROMBY","SABOTSY MANJAKAVAHOAKA","TANKAFATRA","ALAKAMISY","AMBATOMANOINA","AMBOASARY","AMBOHIBARY","AMBOHIMANARINA MAROVAZAHA","AMBOHIMIRARY","AMBONGAMARINA","AMPARATANJONA","ANALAROA","ANDRANOMISA","ANDROVAKELY","ANJOZOROBE","ANTANETIBE","BELANITRA","BERONONO","BETATAO","MANGAMILA","MAROTSIPOY","TSARASOATRA ANDANONA","AMBOHITROMBY","AMBOLOTARAKELY","ANDRANOMIELY SUD","ANKAZOBE","ANTAKAVANA","ANTOTOHAZO","FIADANANA","FIHAONANA","KIANGARA","MAHAVELONA","MANGASOAVINA","MARONDRY","MIANTSO","TALATA-ANGAVO","TSARAMASOANDRO","ALASORA","AMBOHIMALAZA MIRAY","AMBOHIMANAMBOLA","AMBOHIMANGA ROVA","AMBOHIMANGAKELY","AMBOHITRABIBY","ANJEVA GARA","ANKADIKELY ILAFY","ANKADINANDRIANA","ANOSY AVARATRA","FIAFERANA","MANANDRIANA","MASINDRAY","SABOTSY NAMEHANA","TALATA VOLONONDRY","VILIAHAZO","CU ANTANANARIVO (Arr. I)","CU ANTANANARIVO (Arr. II)","CU ANTANANARIVO (ARR.III)","CU ANTANANARIVO (Arr .IV)","CU ANTANANARIVO (Arr. V)","ALAKAMISY FENOARIVO","ALATSINAINY AMBAZAHA","AMBALAVAO","AMBATOFAHAVALO","AMBAVAHADITOKANA","AMBOHIDRAPETO","AMBOHIJANAKA","AMPAHITROSY","AMPANEFY","AMPITATAFIKA","ANDOHARANOFOTSY","ANDRANONAHOATRA","ANDROHIBE","ANKADIMANGA","ANKARAOBATO","ANOSIZATO ANDREFANA","ANTANETIKELY","BEMASOANDRO","BONGATSARA","FENOARIVO","FIOMBONANA","ITAOSY","SOALANDY","SOAVINA","TANJOMBATO","TSIAFAHY","C U ANTANANARIVO ( ARR . VI )","ALAROBIA","AMBANITSENA","AMBATOLOANA","AMBATOMANGA","AMBATOMENA","AMBOHIBAO SUD","AMBOHIBARY","AMBOHITRANDRIAMANITRA","AMBOHITROLOMAHITSY","AMBOHITRONY","AMBOHITSEHENO","AMPANEVA","ANJEPY","ANJOMA BETOHO","ANKAZODANDY","ANTSAHALALINA","MANJAKANDRIANA","MANTASOA","MERIKANJAKA","MIADANANDRIANA","NANDIHIZANA CARION","RANOVAO","SADABE","SAMBAINA","SOAVINANDRIANA"]


reg.length.times do |i|
    Region.create(name: reg[i])
end

alotra.length.times do |i|
    Commune.create(name: alotra[i], region_id: (11))
end

amoro.length.times do |i|
    Commune.create(name: amoro[i], region_id: (14))
end

analamanga.length.times do |i|
    Commune.create(name: analamanga[i], region_id: (4))
end

User.create(full_name: "User",age: 29,adress: "nill", email: "User@user.com", password:"azerty", is_admins: true)
# 10.times do |i|
#     User.create(full_name: Faker::Name.name, age: rand(18..77), adress: Faker::Address.street_address, email: Faker::Internet.email, password: "azertyop")
# end

5.times do |i|
    Candidat.create(name: Faker::FunnyName.name, parti: Faker::Kpop.boy_bands, resultat: rand(99), commune_id: 237, region_id: 4)
end

# 55.times do |i|
#     Promess.create(content: Faker::Kpop.boy_bands, candidat_id: rand(Candidat.first.id .. Candidat.last.id))
# end

puts "vita"